config/routes.rb
Rails.application.routes.draw do
  resources :mensagens
  resources :polos
  resources :usuarios
  resources :respostas
  resources :informacoes
  resources :alvos

  root 'dashboard#index'

  get 'sessoes/new', as: :login
  post 'sessoes/logar'
  get 'sessoes/deslogar', as: :deslogar
  get 'dashboard/index', as: :dashboard
  post 'mensagens/callback', to: 'mensagens#callback'
end

app/models/alvo.rb
class Alvo < ApplicationRecord
  validates :nome, presence: true
  
  include Selectable
end

app/controllers/alvos_controller.rb
class AlvosController < ApplicationController
  before_action :auth_required
  before_action :set_alvo, only: [:show, :edit, :update, :destroy]
  
  def index
      @alvos = Alvo.all
  end

  def edit
  end

  def destroy
    @alvo.destroy
    respond_to do |format|
      format.html { redirect_to alvos_url, notice: 'Alvo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
  end

  def new
    @alvo = Alvo.new
  end
  
  
  def create
    @alvo = Alvo.new(alvo_params)

    respond_to do |format|
      if @alvo.save
        format.html { redirect_to @alvo, notice: 'Alvo was successfully created.' }
        format.json { render :show, status: :created, location: @alvo }
      else
        format.html { render :new }
        format.json { render json: @alvo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @alvo.update(alvo_params)
        format.html { redirect_to @alvo, notice: 'Alvo was successfully updated.' }
        format.json { render :show, status: :ok, location: @alvo }
      else
        format.html { render :edit }
        format.json { render json: @alvo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alvo
      @alvo = Alvo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alvo_params
      params.require(:alvo).permit(:nome)
    end
end

app/helpers/alvos_helper.rb
module AlvosHelper
end

app/views/alvos/_form.html.erb
<%= simple_form_for(@alvo) do |f| %>
  <%= f.input :nome, error: 'Campo obrigatório!' %>
  <%= f.button :submit, 'Enviar', class: 'btn-primary' %>
<% end %>

app/views/alvos/edit.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'user-circle' %> Editar Alvo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('eye', text: 'Detalhar'), @alvo, class: "btn btn-info" %> 
      <%= link_to fa_icon('undo', text: 'Voltar'), alvos_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/alvos/index.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon ' bullseye' %> Alvos</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('plus', text: 'Novo Alvo'), new_alvo_path, class: "btn btn-info" %>
    </div>
  </div>
</div>
<% if @alvos.empty? %>
  <p>Nenhum alvo encontrado.</p>
<% else %>
  <table  class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <% @alvos.each do |alvo| %>
        <tr>
          <td><%= alvo.nome %></td>
        
          <td>
            <div class="btn-group" role="group" aria-label="Opções">
              <%= link_to fa_icon('eye', text: 'Detalhar'), alvo, class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('pencil', text: 'Editar'), edit_alvo_path(alvo), class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('trash', text: 'Apagar'), alvo, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-info" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
 

app/views/alvos/new.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'bullseye' %> Novo Alvo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('undo', text: 'Voltar'), alvos_path, class: "btn btn-info"%>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/alvos/show.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'bullseye' %> Alvo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('pencil', text: 'Editar'), edit_alvo_path(@alvo), class: "btn btn-info"%> 
      <%= link_to fa_icon('trash', text: 'Apagar'), @alvo, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-info" %>
      <%= link_to fa_icon('undo', text: 'Voltar'), alvos_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<dl>
  <dt>Nome</dt><dd><%= @alvo.nome %></dd>
 
</dl>