config/routes.rb
Rails.application.routes.draw do
  resources :mensagens
  resources :polos
  resources :usuarios
  resources :respostas
  resources :informacoes
  resources :alvos

  root 'dashboard#index'

  get 'sessoes/new', as: :login
  post 'sessoes/logar'
  get 'sessoes/deslogar', as: :deslogar
  get 'dashboard/index', as: :dashboard
  post 'mensagens/callback', to: 'mensagens#callback'
end

app/models/resposta.rb
class Resposta < ApplicationRecord
  belongs_to :alvo
  belongs_to :informacao
  has_many :mensagens

  validates :mensagem, presence: true
end

app/controllers/respostas_controller.rb
require 'json'

class RespostasController < ApplicationController
  before_action :auth_required, except: [ :callback ]
  before_action :set_resposta, only: [:show, :edit, :update, :destroy]

  def index
    @respostas = Resposta.all
  end

  def show
  end

  def new
    @alvos = Alvo.all
    @informacoes = Informacao.all
    @resposta = Resposta.new
  end

  def edit
  end

  def create
    @resposta = Resposta.new(resposta_params)

    respond_to do |format|
      if @resposta.save
        format.html { redirect_to @resposta, notice: 'Resposta foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @resposta }
      else
        format.html { render :new }
        format.json { render json: @resposta.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resposta.update(resposta_params)
        format.html { redirect_to @resposta, notice: 'Resposta foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @resposta }
      else
        format.html { render :edit }
        format.json { render json: @resposta.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resposta.destroy
    respond_to do |format|
      format.html { redirect_to respostas_url, notice: 'Resposta foi deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    def set_resposta
      @resposta = Resposta.includes(:alvo, :informacao).find(params[:id])
    end

    def resposta_params
      params.require(:resposta).permit(:mensagem, :alvo_id, :informacao_id)
    end
end

app/helpers/respostas_helper.rb
module RespostasHelper
end

app/views/respostas/_form.html.erb
<%= simple_form_for(@resposta) do |f| %>
  <%= f.input :mensagem, error: 'Campo obrigatório!' %>
  <%= f.input :alvo_id, collection: Alvo.select, prompt: "Escolha um alvo" %>
  <%= f.input :informacao_id, collection: Informacao.select(label: 'tipo'), prompt: "Escolha uma informacao" %>
  <%= f.button :submit, 'Enviar', class: 'btn-primary' %>
<% end %>

app/views/respostas/edit.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'envelope' %> Editar Resposta</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('eye', text: 'Detalhar'), @resposta, class: "btn btn-info" %> 
      <%= link_to fa_icon('undo', text: 'Voltar'), respostas_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/respostas/index.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'envelope' %> Respostas</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('plus', text: 'Nova Resposta'), new_resposta_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<% if @respostas.empty? %>
  <p>Nenhuma resposta encontrada.</p>
<% else %>
  <table  class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Mensagem</th>
        <th>Alvo</th>
        <th>Informação</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <% @respostas.each do |resposta| %>
        <tr>
          <td><%= resposta.mensagem %></td>
          <td><%= resposta.alvo.nome %></td>
          <td><%= resposta.informacao.tipo %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Opções">
              <%= link_to fa_icon('eye', text: 'Detalhar'), resposta, class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('pencil', text: 'Editar'), edit_resposta_path(resposta), class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('trash', text: 'Apagar'), resposta, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-info" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/respostas/new.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'envelope' %> Novo Resposta</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('undo', text: 'Voltar'), respostas_path, class: "btn btn-info"%>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/respostas/show.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'envelope' %> Resposta</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('pencil', text: 'Editar'), edit_resposta_path(@resposta), class: "btn btn-info"%> 
      <%= link_to fa_icon('trash', text: 'Apagar'), @resposta, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-info" %>
      <%= link_to fa_icon('undo', text: 'Voltar'), respostas_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<dl>
  <dt>Mensagem</dt><dd><%= @resposta.mensagem %></dd>
  <dt>Alvo</dt><dd><%= @resposta.alvo.nome %></dd>
  <dt>Informação</dt><dd><%= @resposta.informacao.tipo %></dd>
</dl>