config/routes.rb
Rails.application.routes.draw do
  resources :mensagens
  resources :polos
  resources :usuarios
  resources :respostas
  resources :informacoes
  resources :alvos

  root 'dashboard#index'

  get 'sessoes/new', as: :login
  post 'sessoes/logar'
  get 'sessoes/deslogar', as: :deslogar
  get 'dashboard/index', as: :dashboard
  post 'mensagens/callback', to: 'mensagens#callback'
end

app/models/polo.rb
class Polo < ApplicationRecord
end

app/controllers/polos_controller.rb
class PolosController < ApplicationController
  before_action :set_polo, only: [:show, :edit, :update, :destroy]

  # GET /polos
  # GET /polos.json
  def index
    @polos = Polo.all
  end

  # GET /polos/1
  # GET /polos/1.json
  def show
  end

  # GET /polos/new
  def new
    @polo = Polo.new
  end

  # GET /polos/1/edit
  def edit
  end

  # POST /polos
  # POST /polos.json
  def create
    @polo = Polo.new(polo_params)

    respond_to do |format|
      if @polo.save
        format.html { redirect_to @polo, notice: 'Polo was successfully created.' }
        format.json { render :show, status: :created, location: @polo }
      else
        format.html { render :new }
        format.json { render json: @polo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polos/1
  # PATCH/PUT /polos/1.json
  def update
    respond_to do |format|
      if @polo.update(polo_params)
        format.html { redirect_to @polo, notice: 'Polo was successfully updated.' }
        format.json { render :show, status: :ok, location: @polo }
      else
        format.html { render :edit }
        format.json { render json: @polo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polos/1
  # DELETE /polos/1.json
  def destroy
    @polo.destroy
    respond_to do |format|
      format.html { redirect_to polos_url, notice: 'Polo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polo
      @polo = Polo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def polo_params
      params.require(:polo).permit(:nome)
    end
end

app/helpers/polos_helper.rb
module PolosHelper
end

app/views/polos/_form.html.erb
<%= simple_form_for(@polo) do |f| %>
  <%= f.input :nome, error: 'Campo obrigatório!' %>

  <%= f.button :submit, 'Enviar', class: 'btn-primary' %>
<% end %>

app/views/polos/edit.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'building' %> Editar Polo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('eye', text: 'Detalhar'), @polo, class: "btn btn-info" %> 
      <%= link_to fa_icon('undo', text: 'Voltar'), polos_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/polos/index.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'building' %> Polos</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('plus', text: 'Novo Polo'), new_polo_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<% if @polos.empty? %>
  <p>Nenhum polo encontrado.</p>
<% else %>
  <table  class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <% @polos.each do |polo| %>
        <tr>
          <td><%= polo.nome %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Opções">
              <%= link_to fa_icon('eye', text: 'Detalhar'), polo, class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('pencil', text: 'Editar'), edit_polo_path(polo), class: "btn btn-sm btn-info" %>
              <%= link_to fa_icon('trash', text: 'Apagar'), polo, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-info" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/polos/new.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'building' %> Novo Polo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('undo', text: 'Voltar'), polos_path, class: "btn btn-info"%>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/polos/show.html.erb
<div class="row">
  <div class="col-sm">
    <h1><%= fa_icon 'building' %> Polo</h1>
  </div>
  <div class="col-sm text-right">
    <div class="btn-group" role="group" aria-label="Opções">
      <%= link_to fa_icon('pencil', text: 'Editar'), edit_polo_path(@polo), class: "btn btn-info"%> 
      <%= link_to fa_icon('trash', text: 'Apagar'), @polo, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-info" %>
      <%= link_to fa_icon('undo', text: 'Voltar'), polos_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

<dl>
  <dt>Nome</dt><dd><%= @polo.nome %></dd>
  
</dl>