config/routes.rb
Rails.application.routes.draw do
  resources :mensagens
  resources :polos
  resources :usuarios
  resources :respostas
  resources :informacoes
  resources :alvos

  root 'dashboard#index'

  get 'sessoes/new', as: :login
  post 'sessoes/logar'
  get 'sessoes/deslogar', as: :deslogar
  get 'dashboard/index', as: :dashboard
  post 'mensagens/callback', to: 'mensagens#callback'
end

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
	<div class="alert alert-success" role="alert">
		<%= notice %>
	</div>
<% end %>

<% if alert.present? %>
	<div class="alert alert-danger" role="alert">
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Alan Turing Bot</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="menu">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to fa_icon("navicon", text: "Dashboard"), dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to fa_icon("user-circle", text: "Usuários"), usuarios_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to fa_icon("bullseye", text: "Alvos"), alvos_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to fa_icon("info-circle", text: "Informações"), informacoes_path, class: 'nav-link' %>
      </li>
       <li class="nav-item active">
        <%= link_to fa_icon("building", text: "Polos"), polos_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to fa_icon("envelope", text: "Respostas"), respostas_path, class: 'nav-link' %>
      </li>
       <li class="nav-item active">
        <%= link_to fa_icon("comment", text: "Mensagens"), mensagens_path, class: 'nav-link' %>
      </li>
     
     
      <li class="nav-item active">
        <%= link_to fa_icon("sign-out", text: "Sair"), deslogar_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alan Turing Bot</title>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render partial: 'layouts/menu' if usuario_autenticado? %>
    <div class="container">
      <%= render partial: 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>